name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
env:
  BUILD_TYPE: Release

jobs:
  call-node-workflow:
    uses: ./.github/workflows/node.js.yml
  build:
    needs: call-node-workflow
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    #Global Setup
    - name: arm-none-eabi-gcc GNU Arm Embedded Toolchain
      uses: carlosperate/arm-none-eabi-gcc-action@v1.5.2

    - name: Checkout GP2040-CE
      uses: actions/checkout@v3
    
    # - name: Checkout submodules
    #   working-directory: ${{github.workspace}}
    #   run: git submodule update --init

    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: fsData
        path: ${{github.workspace}}/lib/httpd/

    - name: Checkout pico-sdk/1.4.0
      uses: actions/checkout@v3
      with:
        repository: raspberrypi/pico-sdk
        ref: 1.4.0
        path: pico-sdk
        
    - name: Checkout pico-sdk submodules
      working-directory: ${{github.workspace}}/pico-sdk
      run: git submodule update --init
    
    - name: Get core count
      id: core_count
      run : cat /proc/cpuinfo  | grep processor | wc -l
      #End Global Setup

    - name: PicoW Build Configure CMake
      shell: bash
      run: PICO_SDK_PATH=../pico-sdk GP2040_BOARDCONFIG=PicoW SKIP_WEBBUILD=TRUE cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Pico Build
      shell: bash
      run: GP2040_BOARDCONFIG=PicoW cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel ${{steps.core_count.outputs.output}}
   
    - name: Upload Pico Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: GP2040-CE - PicoW
        path: ${{github.workspace}}/build/GP2040-CE_*_PicoW.uf2
        if-no-files-found: error
        
   
